---
- name: Install tfenv
  become_user: "{{ tfenv_user }}"
  block:
  - name: Clone tfenv repository to home directory
    git:
      repo: https://github.com/tfutils/tfenv.git
      dest: "/home/{{ tfenv_user }}/.tfenv"
      depth: 1
      version: master
  - name: Chmod
    ansible.builtin.file:
      path: "/home/{{ tfenv_user }}/.tfenv"
      state: directory
      mode: '0755'
  - name: Ensure the tfenv path is in .bash_profile
    lineinfile:
      path: "/home/{{ tfenv_user }}/.bashrc"
      line: 'export PATH="$HOME/.tfenv/bin:$PATH"'
      create: yes
    state: link